[supabase]
url = "sb_publishable_TaPjclUgZKAwbOECYk-prA_aVGB-kuQ"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxvY3RuaWJocXRsaXhibmFibmt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE1MTMxOTMsImV4cCI6MjEwNzA4OTE5M30.Rqr8sbbad3bSVOgWeBQnHgIbosNlHSFPeQizuSG691k"

[admin]
default_username = "admin"
default_password = "admin123"
